name: build and test
runs:
  using: ubuntu-latest
  steps:
   - name: npm install, build, and test
     run: |
      npm install
      npm run build --if-present
      npm run test --if-present
