name: A workflow for CI
on: push
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./addDocker
      - uses: actions/setup-node@v1
